#!/bin/bash
if [ $# -le 1 ] ; then
    echo "Usage: buildall <full_sdl2_include_path> <full_sdl2_lib_path> (optional)<nexel_lib64_path>"
    exit 1
fi

SDL_INCLUDE_DIR=$1
SDL_LIB_DIR=$2

rm ./Nexel_Linux/*
mkdir ./Nexel_Linux
mkdir ./SDL2/build
mkdir ./FNA3D/build
mkdir ./FAudio/build

#build SDL2 and copy to /building/
echo ~~~~Building SDL2~~~~
cd ./SDL2/build
cmake ../
make
echo ~~~~Copying SDL2~~~~
cp ./libSDL2-2.0.so.0.14.0 ../../Nexel_Linux/libSDL2-2.0.so.0
cp ./*.a ../../Nexel_Linux

#build FNA3D and copy to /building/
echo ~~~~Building FNA3D~~~~
cd ../../FNA3D/build
cmake -DCMAKE_C_FLAGS=-std=gnu99 -DSDL2_INCLUDE_DIRS=$SDL_INCLUDE_DIR -DSDL2_LIBRARIES=$SDL_LIB_DIR ../
make clean
make
echo ~~~~Copying FNA3D~~~~
cp ./libFNA3D.so.0.21.08 ../../Nexel_Linux/libFNA3D.so.0

#build FAudio and copy to /building/
echo ~~~~Building FAudio~~~~
cd ../../FAudio/build
cmake -DCMAKE_C_FLAGS=-std=gnu99 -DSDL2_INCLUDE_DIRS=$SDL_INCLUDE_DIR -DSDL2_LIBRARIES=$SDL_LIB_DIR ../
make clean
make
echo ~~~~Copying FAudio~~~~
cp ./libFAudio.so.0.21.08 ../../Nexel_Linux/libFAudio.so.0

if [ $# -ge 3 ] ; then
    echo ~~~~Copying to $3~~~~
    cd ../../Nexel_Linux
    cp ./*.0 $3
fi


